Layered navigation system
glow-xyz/nftoken pull request #170
Opened 2022-07-08 16:29 UTC by benborgers

This introduces two levels of navigation: one for the entire NFToken site, and one just for the NFToken docs. 

https://share.cleanshot.com/y932U5

I’m not too sure about the design of the mobile docs nav — happy to hear suggestions for other options! 

## To do

- [ ] Scrolling down on a docs page on mobile and then navigating to another page causes the underline on the primary nav to fly up weirdly. 

## Checklist

- [ ] Splash page looks good in desktop and mobile. 
- [ ] “Learn more” and “Create an NFT” links work. 
- [ ] Sidebar and header show on docs pages and are position: sticky when scrolling. 
- [ ] Docs look good on mobile. 
- [ ] Mobile nav works even when scrolled down the page. 
- [ ] Mobile nav closes when a link is clicked. 
- [ ] Page is not scrollable while mobile nav is open. 
- [ ] Live Minting Demo works. 
- [ ] All pages look good when browser font size is increased (in settings, not cmd+/cmd-). 
- [ ] All pages look good in dark mode. 
- [ ] All pages look good in Safari. 
- [ ] All pages look good in Firefox.

2022-07-08 16:36 UTC, vpontis requested changes
Where would creating a mintlist / creating an NFT live? It feels kinda weird to throw you back to the docs. Should mintlists also have a left sidepanel?

2022-07-08 16:36 UTC, vpontis commented on docs/components/all-pages/Header.tsx
> +              <Link href="/docs/overview">
Can we use `LuxLink` as much as possible?

2022-07-08 16:36 UTC, vpontis commented on docs/components/all-pages/Header.tsx
> +              <Link href="/mintlists">
I think it makes sense to make these easier to extend

```
enum TopLevelTab {}
const TopLevelTabs = [...]

// in render
{TopLevelTabs.map()}
```

2022-07-08 18:38 UTC, benborgers commented
Hmm we could separate out Create an NFT and Create a Mintlist into their own pages outside of the docs, and then group them under Mintlists and NFTs in the main navigation? What do you think of this kinda thing: 

![2022-07-08 at 14 37 31@2x](https://user-images.githubusercontent.com/30215449/178051144-93d99a6c-6d6d-4eea-8db3-71ee14b945e0.png)

2022-07-10 05:42 UTC, vpontis commented
@benborgers I pushed some things here. I didn't like the Android style nav so I tried a two tiered tab system.

2022-07-10 07:19 UTC, vpontis approved these changes

2022-07-10 07:19 UTC, merged

2022-07-10 09:44 UTC, benborgers commented
I really like it!